package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaAreaconvoca generated by hbm2java
 */
@Entity
@Table(name="ma_areaconvoca"
    ,catalog="bdsiifnsp"
)
public class MaAreaconvoca  implements java.io.Serializable {


     private Integer acCod;
     private String acNombre;
     private String acDescripcion;
     private int acHabilitado;
     private Set maAreasintereses = new HashSet(0);

    public MaAreaconvoca() {
    }

	
    public MaAreaconvoca(String acNombre, String acDescripcion, int acHabilitado) {
        this.acNombre = acNombre;
        this.acDescripcion = acDescripcion;
        this.acHabilitado = acHabilitado;
    }
    public MaAreaconvoca(String acNombre, String acDescripcion, int acHabilitado, Set maAreasintereses) {
       this.acNombre = acNombre;
       this.acDescripcion = acDescripcion;
       this.acHabilitado = acHabilitado;
       this.maAreasintereses = maAreasintereses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ac_cod", unique=true, nullable=false)
    public Integer getAcCod() {
        return this.acCod;
    }
    
    public void setAcCod(Integer acCod) {
        this.acCod = acCod;
    }

    
    @Column(name="ac_nombre", nullable=false, length=100)
    public String getAcNombre() {
        return this.acNombre;
    }
    
    public void setAcNombre(String acNombre) {
        this.acNombre = acNombre;
    }

    
    @Column(name="ac_descripcion", nullable=false, length=250)
    public String getAcDescripcion() {
        return this.acDescripcion;
    }
    
    public void setAcDescripcion(String acDescripcion) {
        this.acDescripcion = acDescripcion;
    }

    
    @Column(name="ac_habilitado", nullable=false)
    public int getAcHabilitado() {
        return this.acHabilitado;
    }
    
    public void setAcHabilitado(int acHabilitado) {
        this.acHabilitado = acHabilitado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maAreaconvoca")
    public Set getMaAreasintereses() {
        return this.maAreasintereses;
    }
    
    public void setMaAreasintereses(Set maAreasintereses) {
        this.maAreasintereses = maAreasintereses;
    }




}


