package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaAreaexperiencia generated by hbm2java
 */
@Entity
@Table(name="ma_areaexperiencia"
    ,catalog="bdsiifnsp"
)
public class MaAreaexperiencia  implements java.io.Serializable {


     private Integer aeCod;
     private String aeNombre;
     private int aeHabilitado;
     private Set peExplaborals = new HashSet(0);

    public MaAreaexperiencia() {
    }

	
    public MaAreaexperiencia(int aeHabilitado) {
        this.aeHabilitado = aeHabilitado;
    }
    public MaAreaexperiencia(String aeNombre, int aeHabilitado, Set peExplaborals) {
       this.aeNombre = aeNombre;
       this.aeHabilitado = aeHabilitado;
       this.peExplaborals = peExplaborals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ae_cod", unique=true, nullable=false)
    public Integer getAeCod() {
        return this.aeCod;
    }
    
    public void setAeCod(Integer aeCod) {
        this.aeCod = aeCod;
    }

    
    @Column(name="ae_nombre", length=150)
    public String getAeNombre() {
        return this.aeNombre;
    }
    
    public void setAeNombre(String aeNombre) {
        this.aeNombre = aeNombre;
    }

    
    @Column(name="ae_habilitado", nullable=false)
    public int getAeHabilitado() {
        return this.aeHabilitado;
    }
    
    public void setAeHabilitado(int aeHabilitado) {
        this.aeHabilitado = aeHabilitado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maAreaexperiencia")
    public Set getPeExplaborals() {
        return this.peExplaborals;
    }
    
    public void setPeExplaborals(Set peExplaborals) {
        this.peExplaborals = peExplaborals;
    }




}


