package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaAreasinteres generated by hbm2java
 */
@Entity
@Table(name="ma_areasinteres"
    ,catalog="bdsiifnsp"
)
public class MaAreasinteres  implements java.io.Serializable {


     private Integer aiCod;
     private MaAreaconvoca maAreaconvoca;
     private Date aiFechainicio;
     private Date aiFechafin;
     private String aiNombre;
     private String aiPerfilsolicitado;
     private String aiDoc;
     private Date aiFechapublicacion;
     private String aiTipoadenda;
     private String aiDocadenda;
     private Date aiFechadenda;
     private String aiDocresultados;
     private Set peInteresespersonas = new HashSet(0);

    public MaAreasinteres() {
    }

	
    public MaAreasinteres(MaAreaconvoca maAreaconvoca, String aiNombre) {
        this.maAreaconvoca = maAreaconvoca;
        this.aiNombre = aiNombre;
    }
    public MaAreasinteres(MaAreaconvoca maAreaconvoca, Date aiFechainicio, Date aiFechafin, String aiNombre, String aiPerfilsolicitado, String aiDoc, Date aiFechapublicacion, String aiTipoadenda, String aiDocadenda, Date aiFechadenda, String aiDocresultados, Set peInteresespersonas) {
       this.maAreaconvoca = maAreaconvoca;
       this.aiFechainicio = aiFechainicio;
       this.aiFechafin = aiFechafin;
       this.aiNombre = aiNombre;
       this.aiPerfilsolicitado = aiPerfilsolicitado;
       this.aiDoc = aiDoc;
       this.aiFechapublicacion = aiFechapublicacion;
       this.aiTipoadenda = aiTipoadenda;
       this.aiDocadenda = aiDocadenda;
       this.aiFechadenda = aiFechadenda;
       this.aiDocresultados = aiDocresultados;
       this.peInteresespersonas = peInteresespersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ai_cod", unique=true, nullable=false)
    public Integer getAiCod() {
        return this.aiCod;
    }
    
    public void setAiCod(Integer aiCod) {
        this.aiCod = aiCod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ai_area", nullable=false)
    public MaAreaconvoca getMaAreaconvoca() {
        return this.maAreaconvoca;
    }
    
    public void setMaAreaconvoca(MaAreaconvoca maAreaconvoca) {
        this.maAreaconvoca = maAreaconvoca;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ai_fechainicio", length=10)
    public Date getAiFechainicio() {
        return this.aiFechainicio;
    }
    
    public void setAiFechainicio(Date aiFechainicio) {
        this.aiFechainicio = aiFechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ai_fechafin", length=10)
    public Date getAiFechafin() {
        return this.aiFechafin;
    }
    
    public void setAiFechafin(Date aiFechafin) {
        this.aiFechafin = aiFechafin;
    }

    
    @Column(name="ai_nombre", nullable=false, length=150)
    public String getAiNombre() {
        return this.aiNombre;
    }
    
    public void setAiNombre(String aiNombre) {
        this.aiNombre = aiNombre;
    }

    
    @Column(name="ai_perfilsolicitado", length=65535)
    public String getAiPerfilsolicitado() {
        return this.aiPerfilsolicitado;
    }
    
    public void setAiPerfilsolicitado(String aiPerfilsolicitado) {
        this.aiPerfilsolicitado = aiPerfilsolicitado;
    }

    
    @Column(name="ai_doc", length=50)
    public String getAiDoc() {
        return this.aiDoc;
    }
    
    public void setAiDoc(String aiDoc) {
        this.aiDoc = aiDoc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ai_fechapublicacion", length=10)
    public Date getAiFechapublicacion() {
        return this.aiFechapublicacion;
    }
    
    public void setAiFechapublicacion(Date aiFechapublicacion) {
        this.aiFechapublicacion = aiFechapublicacion;
    }

    
    @Column(name="ai_tipoadenda", length=50)
    public String getAiTipoadenda() {
        return this.aiTipoadenda;
    }
    
    public void setAiTipoadenda(String aiTipoadenda) {
        this.aiTipoadenda = aiTipoadenda;
    }

    
    @Column(name="ai_docadenda", length=50)
    public String getAiDocadenda() {
        return this.aiDocadenda;
    }
    
    public void setAiDocadenda(String aiDocadenda) {
        this.aiDocadenda = aiDocadenda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ai_fechadenda", length=10)
    public Date getAiFechadenda() {
        return this.aiFechadenda;
    }
    
    public void setAiFechadenda(Date aiFechadenda) {
        this.aiFechadenda = aiFechadenda;
    }

    
    @Column(name="ai_docresultados", length=50)
    public String getAiDocresultados() {
        return this.aiDocresultados;
    }
    
    public void setAiDocresultados(String aiDocresultados) {
        this.aiDocresultados = aiDocresultados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maAreasinteres")
    public Set getPeInteresespersonas() {
        return this.peInteresespersonas;
    }
    
    public void setPeInteresespersonas(Set peInteresespersonas) {
        this.peInteresespersonas = peInteresespersonas;
    }




}


