package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaDepartamento generated by hbm2java
 */
@Entity
@Table(name="ma_departamento"
    ,catalog="bdsiifnsp"
)
public class MaDepartamento  implements java.io.Serializable {


     private String dptoCod;
     private String deptoNombre;
     private int dptoHabilitado;
     private Set maMunicipios = new HashSet(0);
     private Set maMunicipios_1 = new HashSet(0);

    public MaDepartamento() {
    }

	
    public MaDepartamento(String dptoCod, int dptoHabilitado) {
        this.dptoCod = dptoCod;
        this.dptoHabilitado = dptoHabilitado;
    }
    public MaDepartamento(String dptoCod, String deptoNombre, int dptoHabilitado, Set maMunicipios, Set maMunicipios_1) {
       this.dptoCod = dptoCod;
       this.deptoNombre = deptoNombre;
       this.dptoHabilitado = dptoHabilitado;
       this.maMunicipios = maMunicipios;
       this.maMunicipios_1 = maMunicipios_1;
    }
   
     @Id 

    
    @Column(name="dpto_cod", unique=true, nullable=false, length=3)
    public String getDptoCod() {
        return this.dptoCod;
    }
    
    public void setDptoCod(String dptoCod) {
        this.dptoCod = dptoCod;
    }

    
    @Column(name="depto_nombre", length=50)
    public String getDeptoNombre() {
        return this.deptoNombre;
    }
    
    public void setDeptoNombre(String deptoNombre) {
        this.deptoNombre = deptoNombre;
    }

    
    @Column(name="dpto_habilitado", nullable=false)
    public int getDptoHabilitado() {
        return this.dptoHabilitado;
    }
    
    public void setDptoHabilitado(int dptoHabilitado) {
        this.dptoHabilitado = dptoHabilitado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maDepartamento")
    public Set getMaMunicipios() {
        return this.maMunicipios;
    }
    
    public void setMaMunicipios(Set maMunicipios) {
        this.maMunicipios = maMunicipios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maDepartamento")
    public Set getMaMunicipios_1() {
        return this.maMunicipios_1;
    }
    
    public void setMaMunicipios_1(Set maMunicipios_1) {
        this.maMunicipios_1 = maMunicipios_1;
    }




}


