package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaDedicacion generated by hbm2java
 */
@Entity
@Table(name="ma_dedicacion"
    ,catalog="bdsiifnsp"
)
public class MaDedicacion  implements java.io.Serializable {


     private Integer ddCod;
     private String ddNombre;
     private Set peExplaborals = new HashSet(0);

    public MaDedicacion() {
    }

	
    public MaDedicacion(String ddNombre) {
        this.ddNombre = ddNombre;
    }
    public MaDedicacion(String ddNombre, Set peExplaborals) {
       this.ddNombre = ddNombre;
       this.peExplaborals = peExplaborals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="dd_cod", unique=true, nullable=false)
    public Integer getDdCod() {
        return this.ddCod;
    }
    
    public void setDdCod(Integer ddCod) {
        this.ddCod = ddCod;
    }

    
    @Column(name="dd_nombre", nullable=false, length=20)
    public String getDdNombre() {
        return this.ddNombre;
    }
    
    public void setDdNombre(String ddNombre) {
        this.ddNombre = ddNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maDedicacion")
    public Set getPeExplaborals() {
        return this.peExplaborals;
    }
    
    public void setPeExplaborals(Set peExplaborals) {
        this.peExplaborals = peExplaborals;
    }




}


