package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaMunicipio generated by hbm2java
 */
@Entity
@Table(name="ma_municipio"
    ,catalog="bdsiifnsp"
)
public class MaMunicipio  implements java.io.Serializable {


     private String codMpio;
     private MaDepartamento maDepartamento;
     private String mpioNombre;
     private Set pePersonasForPeCiudadresidencia = new HashSet(0);
     private Set pePersonasForPeLugarexpced = new HashSet(0);
     private Set pePersonasForPeLugarnacimiento = new HashSet(0);

    public MaMunicipio() {
        this.maDepartamento = new MaDepartamento();
    }

	
    public MaMunicipio(String codMpio) {
        this.codMpio = codMpio;
    }
    public MaMunicipio(String codMpio, MaDepartamento maDepartamento, String mpioNombre, Set pePersonasForPeCiudadresidencia, Set pePersonasForPeLugarexpced, Set pePersonasForPeLugarnacimiento) {
       this.codMpio = codMpio;
       this.maDepartamento = maDepartamento;
       this.mpioNombre = mpioNombre;
       this.pePersonasForPeCiudadresidencia = pePersonasForPeCiudadresidencia;
       this.pePersonasForPeLugarexpced = pePersonasForPeLugarexpced;
       this.pePersonasForPeLugarnacimiento = pePersonasForPeLugarnacimiento;
    }
   
     @Id 

    
    @Column(name="cod_mpio", unique=true, nullable=false, length=6)
    public String getCodMpio() {
        return this.codMpio;
    }
    
    public void setCodMpio(String codMpio) {
        this.codMpio = codMpio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mpio_dpto")
    public MaDepartamento getMaDepartamento() {
        return this.maDepartamento;
    }
    
    public void setMaDepartamento(MaDepartamento maDepartamento) {
        this.maDepartamento = maDepartamento;
    }

    
    @Column(name="mpio_nombre", length=100)
    public String getMpioNombre() {
        return this.mpioNombre;
    }
    
    public void setMpioNombre(String mpioNombre) {
        this.mpioNombre = mpioNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maMunicipioByPeCiudadresidencia")
    public Set getPePersonasForPeCiudadresidencia() {
        return this.pePersonasForPeCiudadresidencia;
    }
    
    public void setPePersonasForPeCiudadresidencia(Set pePersonasForPeCiudadresidencia) {
        this.pePersonasForPeCiudadresidencia = pePersonasForPeCiudadresidencia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maMunicipioByPeLugarexpced")
    public Set getPePersonasForPeLugarexpced() {
        return this.pePersonasForPeLugarexpced;
    }
    
    public void setPePersonasForPeLugarexpced(Set pePersonasForPeLugarexpced) {
        this.pePersonasForPeLugarexpced = pePersonasForPeLugarexpced;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maMunicipioByPeLugarnacimiento")
    public Set getPePersonasForPeLugarnacimiento() {
        return this.pePersonasForPeLugarnacimiento;
    }
    
    public void setPePersonasForPeLugarnacimiento(Set pePersonasForPeLugarnacimiento) {
        this.pePersonasForPeLugarnacimiento = pePersonasForPeLugarnacimiento;
    }




}


