package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaNaturalezainst generated by hbm2java
 */
@Entity
@Table(name="ma_naturalezainst"
    ,catalog="bdsiifnsp"
)
public class MaNaturalezainst  implements java.io.Serializable {


     private Integer niCod;
     private String niNombre;
     private Set peExplaborals = new HashSet(0);

    public MaNaturalezainst() {
    }

    public MaNaturalezainst(String niNombre, Set peExplaborals) {
       this.niNombre = niNombre;
       this.peExplaborals = peExplaborals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ni_cod", unique=true, nullable=false)
    public Integer getNiCod() {
        return this.niCod;
    }
    
    public void setNiCod(Integer niCod) {
        this.niCod = niCod;
    }

    
    @Column(name="ni_nombre", length=10)
    public String getNiNombre() {
        return this.niNombre;
    }
    
    public void setNiNombre(String niNombre) {
        this.niNombre = niNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maNaturalezainst")
    public Set getPeExplaborals() {
        return this.peExplaborals;
    }
    
    public void setPeExplaborals(Set peExplaborals) {
        this.peExplaborals = peExplaborals;
    }




}


