package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaTipoestudio generated by hbm2java
 */
@Entity
@Table(name="ma_tipoestudio"
    ,catalog="bdsiifnsp"
)
public class MaTipoestudio  implements java.io.Serializable {


     private Integer tpCod;
     private int tpCategoria;
     private String tpNombre;
     private Set peEstudioses = new HashSet(0);

    public MaTipoestudio() {
    }

	
    public MaTipoestudio(int tpCategoria) {
        this.tpCategoria = tpCategoria;
    }
    public MaTipoestudio(int tpCategoria, String tpNombre, Set peEstudioses) {
       this.tpCategoria = tpCategoria;
       this.tpNombre = tpNombre;
       this.peEstudioses = peEstudioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tp_cod", unique=true, nullable=false)
    public Integer getTpCod() {
        return this.tpCod;
    }
    
    public void setTpCod(Integer tpCod) {
        this.tpCod = tpCod;
    }

    
    @Column(name="tp_categoria", nullable=false)
    public int getTpCategoria() {
        return this.tpCategoria;
    }
    
    public void setTpCategoria(int tpCategoria) {
        this.tpCategoria = tpCategoria;
    }

    
    @Column(name="tp_nombre", length=20)
    public String getTpNombre() {
        return this.tpNombre;
    }
    
    public void setTpNombre(String tpNombre) {
        this.tpNombre = tpNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maTipoestudio")
    public Set getPeEstudioses() {
        return this.peEstudioses;
    }
    
    public void setPeEstudioses(Set peEstudioses) {
        this.peEstudioses = peEstudioses;
    }




}


