package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaTipoexperiencia generated by hbm2java
 */
@Entity
@Table(name="ma_tipoexperiencia"
    ,catalog="bdsiifnsp"
)
public class MaTipoexperiencia  implements java.io.Serializable {


     private Integer teCod;
     private String teDescirpcion;
     private Set peExplaborals = new HashSet(0);

    public MaTipoexperiencia() {
    }

    public MaTipoexperiencia(String teDescirpcion, Set peExplaborals) {
       this.teDescirpcion = teDescirpcion;
       this.peExplaborals = peExplaborals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="te_cod", unique=true, nullable=false)
    public Integer getTeCod() {
        return this.teCod;
    }
    
    public void setTeCod(Integer teCod) {
        this.teCod = teCod;
    }

    
    @Column(name="te_descirpcion", length=50)
    public String getTeDescirpcion() {
        return this.teDescirpcion;
    }
    
    public void setTeDescirpcion(String teDescirpcion) {
        this.teDescirpcion = teDescirpcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maTipoexperiencia")
    public Set getPeExplaborals() {
        return this.peExplaborals;
    }
    
    public void setPeExplaborals(Set peExplaborals) {
        this.peExplaborals = peExplaborals;
    }




}


