package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaTipoid generated by hbm2java
 */
@Entity
@Table(name="ma_tipoid"
    ,catalog="bdsiifnsp"
)
public class MaTipoid  implements java.io.Serializable {


     private String tiCod;
     private String tiNombre;
     private Set pePersonas = new HashSet(0);

    public MaTipoid() {
    }

	
    public MaTipoid(String tiCod) {
        this.tiCod = tiCod;
    }
    public MaTipoid(String tiCod, String tiNombre, Set pePersonas) {
       this.tiCod = tiCod;
       this.tiNombre = tiNombre;
       this.pePersonas = pePersonas;
    }
   
     @Id 

    
    @Column(name="ti_cod", unique=true, nullable=false, length=3)
    public String getTiCod() {
        return this.tiCod;
    }
    
    public void setTiCod(String tiCod) {
        this.tiCod = tiCod;
    }

    
    @Column(name="ti_nombre", length=40)
    public String getTiNombre() {
        return this.tiNombre;
    }
    
    public void setTiNombre(String tiNombre) {
        this.tiNombre = tiNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maTipoid")
    public Set getPePersonas() {
        return this.pePersonas;
    }
    
    public void setPePersonas(Set pePersonas) {
        this.pePersonas = pePersonas;
    }




}


