package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MaUsuario generated by hbm2java
 */
@Entity
@Table(name = "ma_usuario", catalog = "bdsiifnsp"
)
public class MaUsuario implements java.io.Serializable {

    private Integer usId;
    private PePersona pePersona;
    private MaPerfil maPerfil;
    private String usClave;

    public MaUsuario() {
        this.pePersona = new PePersona();
        this.maPerfil = new MaPerfil();
    }

    public MaUsuario(PePersona pePersona) {
        this.pePersona = pePersona;
    }

    public MaUsuario(PePersona pePersona, MaPerfil maPerfil, String usClave) {
        this.pePersona = pePersona;
        this.maPerfil = maPerfil;
        this.usClave = usClave;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "us_id", unique = true, nullable = false)
    public Integer getUsId() {
        return this.usId;
    }

    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "us_persona", nullable = false)
    public PePersona getPePersona() {
        return this.pePersona;
    }

    public void setPePersona(PePersona pePersona) {
        this.pePersona = pePersona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "us_perfil")
    public MaPerfil getMaPerfil() {
        return this.maPerfil;
    }

    public void setMaPerfil(MaPerfil maPerfil) {
        this.maPerfil = maPerfil;
    }

    @Column(name = "us_clave", length = 50)
    public String getUsClave() {
        return this.usClave;
    }

    public void setUsClave(String usClave) {
        this.usClave = usClave;
    }

}
