package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeEstudios generated by hbm2java
 */
@Entity
@Table(name="pe_estudios"
    ,catalog="bdsiifnsp"
)
public class PeEstudios  implements java.io.Serializable {


     private Integer estCod;
     private MaAreaestudio maAreaestudio;
     private MaTipoestudio maTipoestudio;
     private PePersona pePersona;
     private String estNombreestudio;
     private String estInstitucion;
     private String estAnio;
     private String estDuracion;
     private String estEstado;
     private String estCertificado;
     private String estUrl;
     private String estArchivo;
     private Date estUpdate; 

    public PeEstudios() {
        this.maAreaestudio = new MaAreaestudio();
        this.maTipoestudio = new MaTipoestudio();
    }

    public PeEstudios(MaAreaestudio maAreaestudio, MaTipoestudio maTipoestudio, PePersona pePersona, String estNombreestudio, String estInstitucion, String estAnio, String estDuracion, String estEstado, String estCertificado) {
       this.maAreaestudio = maAreaestudio;
       this.maTipoestudio = maTipoestudio;
       this.pePersona = pePersona;
       this.estNombreestudio = estNombreestudio;
       this.estInstitucion = estInstitucion;
       this.estAnio = estAnio;
       this.estDuracion = estDuracion;
       this.estEstado = estEstado;
       this.estCertificado = estCertificado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="est_cod", unique=true, nullable=false)
    public Integer getEstCod() {
        return this.estCod;
    }
    
    public void setEstCod(Integer estCod) {
        this.estCod = estCod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="est_area")
    public MaAreaestudio getMaAreaestudio() {
        return this.maAreaestudio;
    }
    
    public void setMaAreaestudio(MaAreaestudio maAreaestudio) {
        this.maAreaestudio = maAreaestudio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="est_tipo")
    public MaTipoestudio getMaTipoestudio() {
        return this.maTipoestudio;
    }
    
    public void setMaTipoestudio(MaTipoestudio maTipoestudio) {
        this.maTipoestudio = maTipoestudio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="est_persona")
    public PePersona getPePersona() {
        return this.pePersona;
    }
    
    public void setPePersona(PePersona pePersona) {
        this.pePersona = pePersona;
    }

    
    @Column(name="est_nombreestudio", length=250)
    public String getEstNombreestudio() {
        return this.estNombreestudio;
    }
    
    public void setEstNombreestudio(String estNombreestudio) {
        this.estNombreestudio = estNombreestudio;
    }

    
    @Column(name="est_institucion", length=150)
    public String getEstInstitucion() {
        return this.estInstitucion;
    }
    
    public void setEstInstitucion(String estInstitucion) {
        this.estInstitucion = estInstitucion;
    }

    
    @Column(name="est_anio", length=4)
    public String getEstAnio() {
        return this.estAnio;
    }
    
    public void setEstAnio(String estAnio) {
        this.estAnio = estAnio;
    }

    
    @Column(name="est_duracion", length=50)
    public String getEstDuracion() {
        return this.estDuracion;
    }
    
    public void setEstDuracion(String estDuracion) {
        this.estDuracion = estDuracion;
    }

    
    @Column(name="est_estado", length=150)
    public String getEstEstado() {
        return this.estEstado;
    }
    
    public void setEstEstado(String estEstado) {
        this.estEstado = estEstado;
    }

    
    @Column(name="est_certificado", length=250)
    public String getEstCertificado() {
        return this.estCertificado;
    }
    
    public void setEstCertificado(String estCertificado) {
        this.estCertificado = estCertificado;
    }

    @Column(name="est_url", length=250)
    public String getEstUrl() {
        return this.estUrl;
    }
    
    public void setEstUrl(String estUrl) {
        this.estUrl = estUrl;
    }
    
    @Column(name="est_archivo", length=20)
    public String getEstArchivo() {
        return this.estArchivo;
    }
    
    public void setEstArchivo(String estArchivo) {
        this.estArchivo = estArchivo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "est_update",  length = 19)
    public Date getEstUpdate() {
        return estUpdate;
    }

    public void setEstUpdate(Date estUpdate) {
        this.estUpdate = estUpdate;
    }    



}


