package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeExplaboral generated by hbm2java
 */
@Entity
@Table(name = "pe_explaboral", catalog = "bdsiifnsp"
)
public class PeExplaboral implements java.io.Serializable {

    private Integer epCod;
    private MaDedicacion maDedicacion;
    private MaNaturalezainst maNaturalezainst;
    private MaAreaexperiencia maAreaexperiencia;
    private PePersona pePersona;
    private MaTipoexperiencia maTipoexperiencia;
    private String epCargo;
    private String epInstitucion;
    private Date epFechaingreso;
    private Date epFecharetiro;
    private String epActual;
    private String epCertificado;
    private String epUrl;
    private String epArchivo;
    private Date epFecharegistro;

    public PeExplaboral() {
        this.maDedicacion = new MaDedicacion();
        this.maAreaexperiencia = new MaAreaexperiencia();
        this.maNaturalezainst = new MaNaturalezainst();
        this.maTipoexperiencia = new MaTipoexperiencia();
    }

    public PeExplaboral(Date epFecharegistro) {
        this.epFecharegistro = epFecharegistro;
    }

    public PeExplaboral(MaDedicacion maDedicacion, MaNaturalezainst maNaturalezainst, MaAreaexperiencia maAreaexperiencia, PePersona pePersona, MaTipoexperiencia maTipoexperiencia, String epCargo, String epInstitucion, Date epFechaingreso, Date epFecharetiro, String epActual, String epCertificado, Date epFecharegistro) {
        this.maDedicacion = maDedicacion;
        this.maNaturalezainst = maNaturalezainst;
        this.maAreaexperiencia = maAreaexperiencia;
        this.pePersona = pePersona;
        this.maTipoexperiencia = maTipoexperiencia;
        this.epCargo = epCargo;
        this.epInstitucion = epInstitucion;
        this.epFechaingreso = epFechaingreso;
        this.epFecharetiro = epFecharetiro;
        this.epActual = epActual;
        this.epCertificado = epCertificado;
        this.epFecharegistro = epFecharegistro;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ep_cod", unique = true, nullable = false)
    public Integer getEpCod() {
        return this.epCod;
    }

    public void setEpCod(Integer epCod) {
        this.epCod = epCod;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ep_dedicacion")
    public MaDedicacion getMaDedicacion() {
        return this.maDedicacion;
    }

    public void setMaDedicacion(MaDedicacion maDedicacion) {
        this.maDedicacion = maDedicacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ep_tipoinstitucion")
    public MaNaturalezainst getMaNaturalezainst() {
        return this.maNaturalezainst;
    }

    public void setMaNaturalezainst(MaNaturalezainst maNaturalezainst) {
        this.maNaturalezainst = maNaturalezainst;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ep_area")
    public MaAreaexperiencia getMaAreaexperiencia() {
        return this.maAreaexperiencia;
    }

    public void setMaAreaexperiencia(MaAreaexperiencia maAreaexperiencia) {
        this.maAreaexperiencia = maAreaexperiencia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ep_persona")
    public PePersona getPePersona() {
        return this.pePersona;
    }

    public void setPePersona(PePersona pePersona) {
        this.pePersona = pePersona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ep_tipoexperiencia")
    public MaTipoexperiencia getMaTipoexperiencia() {
        return this.maTipoexperiencia;
    }

    public void setMaTipoexperiencia(MaTipoexperiencia maTipoexperiencia) {
        this.maTipoexperiencia = maTipoexperiencia;
    }

    @Column(name = "ep_cargo", length = 250)
    public String getEpCargo() {
        return this.epCargo;
    }

    public void setEpCargo(String epCargo) {
        this.epCargo = epCargo;
    }

    @Column(name = "ep_institucion", length = 250)
    public String getEpInstitucion() {
        return this.epInstitucion;
    }

    public void setEpInstitucion(String epInstitucion) {
        this.epInstitucion = epInstitucion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ep_fechaingreso", length = 10)
    public Date getEpFechaingreso() {
        return this.epFechaingreso;
    }

    public void setEpFechaingreso(Date epFechaingreso) {
        this.epFechaingreso = epFechaingreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ep_fecharetiro", length = 10)
    public Date getEpFecharetiro() {
        return this.epFecharetiro;
    }

    public void setEpFecharetiro(Date epFecharetiro) {
        this.epFecharetiro = epFecharetiro;
    }

    @Column(name = "ep_actual", length = 2)
    public String getEpActual() {
        return this.epActual;
    }

    public void setEpActual(String epActual) {
        this.epActual = epActual;
    }

    @Column(name = "ep_certificado", length = 250)
    public String getEpCertificado() {
        return this.epCertificado;
    }

    public void setEpCertificado(String epCertificado) {
        this.epCertificado = epCertificado;
    }

    @Column(name="ep_url", length=250)
    public String getEpUrl() {
        return epUrl;
    }

    public void setEpUrl(String epUrl) {
        this.epUrl = epUrl;
    }

    @Column(name="ep_archivo", length=20)
    public String getEpArchivo() {
        return epArchivo;
    }

    public void setEpArchivo(String epArchivo) {
        this.epArchivo = epArchivo;
    }       

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ep_fecharegistro", nullable = false, length = 19)
    public Date getEpFecharegistro() {
        return this.epFecharegistro;
    }

    public void setEpFecharegistro(Date epFecharegistro) {
        this.epFecharegistro = epFecharegistro;
    }

}
