package com.udea.fnsp.buho.modelo;
// Generated 25/06/2014 12:01:44 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeInteresespersona generated by hbm2java
 */
@Entity
@Table(name="pe_interesespersona"
    ,catalog="bdsiifnsp"
)
public class PeInteresespersona  implements java.io.Serializable {


     private Integer ipCod;
     private PePersona pePersona;
     private MaAreasinteres maAreasinteres;
     private Integer ipHabilitado;
     private String ipPreseleccion;
     private Date ipFecharegistro;

    public PeInteresespersona() {
    }

	
    public PeInteresespersona(MaAreasinteres maAreasinteres) {
        this.maAreasinteres = maAreasinteres;
    }
    public PeInteresespersona(PePersona pePersona, MaAreasinteres maAreasinteres, Integer ipHabilitado, String ipPreseleccion, Date ipFecharegistro) {
       this.pePersona = pePersona;
       this.maAreasinteres = maAreasinteres;
       this.ipHabilitado = ipHabilitado;
       this.ipPreseleccion = ipPreseleccion;
       this.ipFecharegistro = ipFecharegistro;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ip_cod", unique=true, nullable=false)
    public Integer getIpCod() {
        return this.ipCod;
    }
    
    public void setIpCod(Integer ipCod) {
        this.ipCod = ipCod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ip_persona")
    public PePersona getPePersona() {
        return this.pePersona;
    }
    
    public void setPePersona(PePersona pePersona) {
        this.pePersona = pePersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ip_area", nullable=false)
    public MaAreasinteres getMaAreasinteres() {
        return this.maAreasinteres;
    }
    
    public void setMaAreasinteres(MaAreasinteres maAreasinteres) {
        this.maAreasinteres = maAreasinteres;
    }

    
    @Column(name="ip_habilitado")
    public Integer getIpHabilitado() {
        return this.ipHabilitado;
    }
    
    public void setIpHabilitado(Integer ipHabilitado) {
        this.ipHabilitado = ipHabilitado;
    }

    
    @Column(name="ip_preseleccion", length=2)
    public String getIpPreseleccion() {
        return this.ipPreseleccion;
    }
    
    public void setIpPreseleccion(String ipPreseleccion) {
        this.ipPreseleccion = ipPreseleccion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ip_fecharegistro", length=19)
    public Date getIpFecharegistro() {
        return this.ipFecharegistro;
    }
    
    public void setIpFecharegistro(Date ipFecharegistro) {
        this.ipFecharegistro = ipFecharegistro;
    }




}


